--猛毒性 石化凝视
function c24562473.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetCountLimit(1,24562473)
	e1:SetTarget(c24562473.target)
	e1:SetOperation(c24562473.activate)
	c:RegisterEffect(e1)
	local e0=Effect.CreateEffect(c)
	e0:SetDescription(aux.Stringid(24562471,4))
	e0:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e0:SetProperty(EFFECT_FLAG_DELAY)
	e0:SetCountLimit(1,24562450)
	e0:SetCode(EVENT_REMOVE)
	e0:SetOperation(c24562473.dmg)
	c:RegisterEffect(e0)
end
function c24562473.dmg(e,tp,eg,ep,ev,re,r,rp,chk)
	local c=e:GetHandler()
	c:SetTurnCounter(0)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_PHASE+PHASE_END)
	e1:SetOperation(c24562473.checkop)
	e1:SetCountLimit(1)
	e1:SetReset(RESET_EVENT+RESET_PHASE+PHASE_END,5)
	Duel.RegisterEffect(e1,1-tp)
	c:RegisterFlagEffect(24562473,RESET_PHASE+PHASE_END,0,5)
	c24562473[c]=e1
end
function c24562473.checkop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local ct=c:GetTurnCounter()
	ct=ct+1
	c:SetTurnCounter(ct)
	if ct<5 then
		Duel.Hint(HINT_CARD,0,24562473)
		Duel.Damage(tp,300,REASON_EFFECT,true)
		Duel.RDComplete()
	end
	if ct==5 then
		Duel.Hint(HINT_CARD,0,24562473)
		Duel.Damage(tp,2000,REASON_EFFECT,true)
		Duel.RDComplete()
		c:ResetFlagEffect(24562473)
	end
end
function c24562473.target(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetLocationCount(1-tp,LOCATION_MZONE)>0 and Duel.GetMatchingGroupCount(c24562473.fil1,tp,0,LOCATION_SZONE,nil,e,tp)>0 end
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,0,0)
end
function c24562473.fil1(c,e,tp)
	local tp=e:GetHandler():GetControler()
	return c:IsFaceup() and Duel.IsPlayerCanSpecialSummonMonster(tp,24562464,0x9390,TYPE_NORMAL,700,700,1,RACE_ROCK,ATTRIBUTE_EARTH,POS_FACEUP_ATTACK,1-tp) and not c:IsFusionType(TYPE_MONSTER)
end
function c24562473.activate(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	if Duel.GetLocationCount(1-tp,LOCATION_MZONE)<=0 and Duel.GetMatchingGroupCount(c24562473.fil1,tp,0,nil,e,tp)<=0 then return end
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(24562473,0))
	local g=Duel.SelectMatchingCard(tp,c24562473.fil1,tp,0,LOCATION_SZONE,1,1,nil,e,tp)
	local tc=g:GetFirst()
	if tc then
	tc:AddMonsterAttribute(TYPE_NORMAL,ATTRIBUTE_EARTH,RACE_ROCK,1,650,1250)
	Duel.SpecialSummonStep(tc,0,tp,1-tp,true,false,POS_FACEUP_ATTACK)
	tc:AddMonsterAttributeComplete()
		local e9=Effect.CreateEffect(c)
		e9:SetDescription(aux.Stringid(24562473,1))
		e9:SetType(EFFECT_TYPE_SINGLE)
		e9:SetCode(EFFECT_CHANGE_CODE)
		e9:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_CLIENT_HINT)
		e9:SetValue(24562464)
		e9:SetReset(RESET_EVENT+0x1fe0000)
		tc:RegisterEffect(e9)
		local e3=Effect.CreateEffect(c)
		e3:SetType(EFFECT_TYPE_SINGLE)
		e3:SetCode(EFFECT_LEAVE_FIELD_REDIRECT)
		e3:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e3:SetReset(RESET_EVENT+RESETS_STANDARD-RESET_TOFIELD)
		e3:SetValue(LOCATION_REMOVED)
		tc:RegisterEffect(e3)
		local e1=Effect.CreateEffect(c)
		e1:SetDescription(aux.Stringid(24562473,2))
		e1:SetType(EFFECT_TYPE_SINGLE)
		e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_CLIENT_HINT)
		e1:SetCode(EFFECT_CANNOT_CHANGE_POS_E)
		e1:SetRange(LOCATION_MZONE)
		e1:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e1)
		local e8=Effect.CreateEffect(c)
		e8:SetDescription(aux.Stringid(24562473,3))
		e8:SetType(EFFECT_TYPE_SINGLE)
		e8:SetCode(EFFECT_CANNOT_CHANGE_POSITION)
		e8:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_CLIENT_HINT)
		e8:SetRange(LOCATION_MZONE)
		e8:SetReset(RESET_EVENT+RESETS_STANDARD)
		tc:RegisterEffect(e8)
	Duel.SpecialSummonComplete()
	end
end
function c24562473.spcon(e,tp,eg,ep,ev,re,r,rp)
	return e:IsFacedown()
end
